import type { Metadata } from "next";
import { Charis_SIL, Inter } from "next/font/google";
import "./globals.css";

const charis = Charis_SIL({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-charis",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${charis.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
